# Generated by Django 4.0.6 on 2022-07-14 16:51

import authentication.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_managers_user_groups_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[authentication.validations.validate_phone_length, authentication.validations.validate_phone_starts_with_plus, authentication.validations.validate_phone_is_num], verbose_name='phone number'),
        ),
    ]
