# Generated by Django 4.0.6 on 2022-07-22 19:30

import authentication.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_avatar_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Supported content types: jpg, jpeg, png .', null=True, upload_to='avatars/', validators=[authentication.validations.validate_image_extension]),
        ),
    ]
