# Generated by Django 4.0.6 on 2022-07-24 13:08

import authentication.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Password must contains at lest one (capital character, small character, digit, special character) and must be at lest 8 characters', max_length=128, validators=[authentication.validations.validate_password_length, authentication.validations.validate_password], verbose_name='password'),
        ),
    ]
