# Generated by Django 4.0.6 on 2022-07-25 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_is_active_confirmationcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcodes',
            name='code',
            field=models.CharField(editable=False, max_length=9),
        ),
        migrations.AlterField(
            model_name='confirmationcodes',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 11, 54, 20, 449423)),
        ),
    ]
