# Generated by Django 4.0.6 on 2022-07-25 12:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_confirmationcodes_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcodes',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 12, 12, 33, 938400, tzinfo=utc)),
        ),
    ]
